FROM python:3.11-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade -y

WORKDIR /back
COPY ./requirements.txt ./
RUN pip install -r ./requirements.txt
# RUN pip uninstall -y gunicorn
# RUN pip install -y uwsgi

COPY ./parser ./parser

COPY ./config.py ./

COPY ./entrypoint.parser.sh ./
RUN chmod +x entrypoint.parser.sh
ENTRYPOINT ["bash", "entrypoint.parser.sh"]
